[project]
name = "tobicross"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python =  ">=3.12, <3.14"
dependencies = [
    "faiss-cpu>=1.13.2",
    "openai>=2.30.0",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.3.0",
    "streamlit>=1.56.0",
    "streamlit-card>=1.0.2",
    "torch",
    "torchvision",
]
